
-- ══════════════════════════════════════════════
-- GHANA MATHEMATICS
-- ══════════════════════════════════════════════

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_P1','GH_MATH','Mathematics','[{"name":"Number","topics":[{"name":"Counting and Numbers","subtopics":["Counting objects 1 to 100","Reading and writing numbers 1 to 100","Ordering numbers","Comparing numbers","Skip counting in 2s, 5s and 10s"]},{"name":"Place Value","subtopics":["Tens and ones","Grouping in tens","Number lines"]},{"name":"Fractions","subtopics":["Half of a whole shape","Quarter of a whole shape","Sharing equally"]}]},{"name":"Operations","topics":[{"name":"Addition","subtopics":["Adding numbers within 20","Number bonds to 10 and 20","Adding on a number line"]},{"name":"Subtraction","subtopics":["Subtracting within 20","Taking away","Difference between numbers"]}]},{"name":"Measurement","topics":[{"name":"Length and Mass","subtopics":["Comparing lengths","Comparing weights","Measuring using non-standard units"]},{"name":"Time","subtopics":["Days of the week","Morning and afternoon","Telling time to the hour"]}]},{"name":"Geometry","topics":[{"name":"Shapes","subtopics":["Identifying circles, squares, triangles and rectangles","Sorting shapes","Patterns with shapes"]}]}]','{"by_end_of_year":["Count and write numbers to 100","Add and subtract within 20","Identify basic 2D shapes","Compare lengths and weights","Tell time to the hour"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_P2','GH_MATH','Mathematics','[{"name":"Number","topics":[{"name":"Numbers to 999","subtopics":["Reading and writing numbers to 999","Hundreds, tens and ones","Comparing and ordering","Even and odd numbers"]},{"name":"Fractions","subtopics":["Halves and quarters of shapes","Halves and quarters of quantities"]}]},{"name":"Operations","topics":[{"name":"Addition and Subtraction","subtopics":["Adding and subtracting 2-digit numbers","Adding with carrying","Subtracting with borrowing","Word problems"]},{"name":"Multiplication","subtopics":["Repeated addition","2, 3, 5 and 10 times tables","Arrays"]},{"name":"Division","subtopics":["Sharing into equal groups","Dividing by 2, 5 and 10"]}]},{"name":"Measurement","topics":[{"name":"Length","subtopics":["Measuring in centimetres and metres"]},{"name":"Money","subtopics":["Ghanaian cedis and pesewas","Adding and subtracting money","Shopping problems"]},{"name":"Time","subtopics":["Telling time to the half hour","Days and months"]}]},{"name":"Geometry","topics":[{"name":"Shapes","subtopics":["Properties of 2D shapes","Introduction to 3D shapes","Lines of symmetry"]}]}]','{"by_end_of_year":["Read and write numbers to 999","Know 2, 3, 5 and 10 times tables","Add and subtract 2-digit numbers","Use Ghanaian currency","Tell time to the half hour"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_P3','GH_MATH','Mathematics','[{"name":"Number","topics":[{"name":"Numbers to 9999","subtopics":["Place value to thousands","Rounding to nearest 10 and 100","Roman numerals I to X"]},{"name":"Fractions","subtopics":["Proper fractions","Equivalent fractions","Comparing fractions","Fractions of quantities"]}]},{"name":"Operations","topics":[{"name":"Multiplication and Division","subtopics":["Times tables 1 to 10","Multiplying 2-digit by 1-digit","Dividing 2-digit by 1-digit","Word problems"]},{"name":"Addition and Subtraction","subtopics":["Adding and subtracting 3-digit numbers","Column method","Checking using inverse"]}]},{"name":"Measurement","topics":[{"name":"Length, Mass and Capacity","subtopics":["Measuring in km, m, cm","Kg and g","Litres and ml"]},{"name":"Perimeter and Area","subtopics":["Perimeter of rectangles","Area by counting squares"]}]},{"name":"Geometry","topics":[{"name":"Angles and Shapes","subtopics":["Right angles","Types of triangles","Quadrilaterals","3D shapes"]}]},{"name":"Data Handling","topics":[{"name":"Charts and Graphs","subtopics":["Tally charts","Bar charts","Pictograms","Reading and interpreting data"]}]}]','{"by_end_of_year":["Know all times tables to 10","Add and subtract 3-digit numbers","Find equivalent fractions","Calculate perimeter and area of rectangles","Read and interpret bar charts"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_P4','GH_MATH','Mathematics','[{"name":"Number","topics":[{"name":"Numbers to 99,999","subtopics":["Place value to ten-thousands","Factors and multiples","LCM and HCF","Square numbers"]},{"name":"Fractions and Decimals","subtopics":["Adding and subtracting fractions","Mixed numbers","Decimal notation","Rounding decimals"]}]},{"name":"Operations","topics":[{"name":"Multiplication and Division","subtopics":["Multiplying 3-digit by 2-digit","Long division","BODMAS introduction","Word problems"]}]},{"name":"Measurement","topics":[{"name":"Area and Perimeter","subtopics":["Area of composite shapes","Perimeter of irregular shapes"]},{"name":"Time","subtopics":["24-hour clock","Calculating time intervals","Timetables"]}]},{"name":"Geometry","topics":[{"name":"Angles","subtopics":["Measuring angles with a protractor","Angles in a triangle","Vertically opposite angles"]},{"name":"Coordinates","subtopics":["Plotting points in first quadrant","Reading coordinates"]}]},{"name":"Data and Probability","topics":[{"name":"Statistics","subtopics":["Mean, median, mode","Frequency tables","Line graphs"]},{"name":"Probability","subtopics":["Likelihood scale","Simple probability fractions"]}]}]','{"by_end_of_year":["Work with numbers to 99,999","Multiply 3-digit by 2-digit","Add and subtract fractions","Calculate mean, median and mode","Use 24-hour clock"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_P5','GH_MATH','Mathematics','[{"name":"Number","topics":[{"name":"Numbers to 1,000,000","subtopics":["Reading and writing large numbers","Prime and composite numbers","Squares and square roots","Index notation"]},{"name":"Fractions, Decimals and Percentages","subtopics":["All operations with fractions","Converting between forms","Percentage of a quantity","Profit and loss"]}]},{"name":"Algebra","topics":[{"name":"Introduction to Algebra","subtopics":["Using letters for unknowns","Simple equations","Number sequences and patterns"]}]},{"name":"Measurement","topics":[{"name":"Volume","subtopics":["Volume of cuboids","Units of volume","Real-life applications"]},{"name":"Ratio and Proportion","subtopics":["Simplifying ratios","Dividing in a ratio","Direct proportion"]}]},{"name":"Geometry","topics":[{"name":"Shapes","subtopics":["Properties of polygons","Circles: radius, diameter, circumference","Constructions"]},{"name":"Transformations","subtopics":["Reflection","Rotation","Translation"]}]},{"name":"Statistics","topics":[{"name":"Data Handling","subtopics":["Frequency distributions","Pie charts","Probability: theoretical and experimental"]}]}]','{"by_end_of_year":["Work with numbers to 1,000,000","Calculate percentages including profit and loss","Solve simple algebraic equations","Calculate volume of cuboids","Apply ratio and proportion"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_P6','GH_MATH','Mathematics','[{"name":"Number","topics":[{"name":"Number Theory","subtopics":["LCM and HCF of large numbers","Standard form","Significant figures","Rational and irrational numbers"]},{"name":"Ratio and Proportion","subtopics":["Ratio problems","Map scales","Direct and inverse proportion","Financial mathematics: interest, discount, commission"]}]},{"name":"Algebra","topics":[{"name":"Algebraic Expressions","subtopics":["Expanding brackets","Factorising","Solving linear equations","Substitution into formulae"]}]},{"name":"Geometry","topics":[{"name":"Plane Geometry","subtopics":["Angles in parallel lines","Pythagoras theorem","Circle: arc, chord, tangent","Properties of polygons"]},{"name":"Mensuration","subtopics":["Circumference and area of circles","Volume of prisms","Surface area of cuboids"]}]},{"name":"Statistics","topics":[{"name":"Data Analysis","subtopics":["Mean from frequency tables","Cumulative frequency","Probability: combined events","Misleading statistics"]}]}]','{"by_end_of_year":["Apply ratio and proportion to real-life problems","Expand and factorise expressions","Apply Pythagoras theorem","Calculate circumference, area and volume","Interpret cumulative frequency graphs"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_JHS1','GH_MATH','Mathematics','[{"name":"Number and Numeration","topics":[{"name":"Number Bases","subtopics":["Binary, octal and other bases","Converting between bases","Operations in different bases"]},{"name":"Directed Numbers","subtopics":["Operations with integers","Number line","Real-life applications"]}]},{"name":"Algebra","topics":[{"name":"Expressions and Equations","subtopics":["Expanding and factorising","Linear equations","Simultaneous equations","Word problems"]},{"name":"Sequences","subtopics":["Linear sequences: nth term","Quadratic sequences","Geometric sequences"]}]},{"name":"Geometry","topics":[{"name":"Angles and Shapes","subtopics":["Angles in parallel lines","Angles in polygons","Congruence and similarity","Constructions"]},{"name":"Mensuration","subtopics":["Area of triangles and parallelograms","Circumference and area of circles","Volume of cylinders and prisms"]}]},{"name":"Statistics","topics":[{"name":"Data Handling","subtopics":["Frequency tables and histograms","Mean, median, mode from grouped data","Pie charts","Scatter graphs"]}]}]','{"by_end_of_year":["Convert between number bases","Solve simultaneous equations","Apply properties of angles and shapes","Calculate areas and volumes","Interpret histograms and scatter graphs"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_JHS2','GH_MATH','Mathematics','[{"name":"Number","topics":[{"name":"Surds and Indices","subtopics":["Simplifying surds","Laws of indices","Fractional and negative indices","Standard form"]}]},{"name":"Algebra","topics":[{"name":"Quadratic Equations","subtopics":["Factorising quadratics","Completing the square","Quadratic formula","Nature of roots"]},{"name":"Graphs","subtopics":["Straight line graphs","Quadratic curves","Gradient and intercept","Graphical solution of equations"]},{"name":"Inequalities","subtopics":["Linear inequalities","Graphing on number line","Quadratic inequalities"]}]},{"name":"Geometry","topics":[{"name":"Trigonometry","subtopics":["Sin, cos, tan ratios","Finding angles and sides","Angles of elevation and depression","Bearings"]},{"name":"Transformations","subtopics":["Reflection, rotation, translation","Enlargement","Combined transformations"]}]},{"name":"Statistics","topics":[{"name":"Probability","subtopics":["Tree diagrams","Addition and multiplication rules","Conditional probability","Experimental probability"]}]}]','{"by_end_of_year":["Work with surds and indices","Solve quadratic equations by all methods","Apply trigonometry to find angles and sides","Interpret linear and quadratic graphs","Apply probability rules and tree diagrams"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_JHS3','GH_MATH','Mathematics','[{"name":"Number and Algebra","topics":[{"name":"Revision and Extension","subtopics":["Comprehensive number revision","Algebraic manipulation","Functions and mappings","Linear programming"]},{"name":"Matrices","subtopics":["Matrix notation","Operations on matrices","Determinant","Inverse matrix"]}]},{"name":"Geometry","topics":[{"name":"Circle Theorems","subtopics":["All circle theorems","Proofs","Applications"]},{"name":"Mensuration","subtopics":["Surface area and volume of spheres and cones","Frustums","Density calculations"]}]},{"name":"Statistics","topics":[{"name":"Data Analysis","subtopics":["Cumulative frequency and ogive","Quartiles and interquartile range","Box plots","Variance and standard deviation"]}]},{"name":"BECE Preparation","topics":[{"name":"Exam Technique","subtopics":["BECE past questions","Objective test strategies","Essay questions","Time management"]}]}]','{"by_end_of_year":["Perform matrix operations","Apply all circle theorems","Calculate surface area and volume of all 3D shapes","Interpret cumulative frequency and box plots","Prepare for BECE Mathematics examination"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_SHS1','GH_MATH','Mathematics','[{"name":"Pure Mathematics","topics":[{"name":"Sets and Algebra","subtopics":["Set theory and Venn diagrams","Polynomials","Remainder and factor theorems","Partial fractions"]},{"name":"Functions","subtopics":["Domain and range","Composite functions","Inverse functions","Graphs of functions"]},{"name":"Logarithms","subtopics":["Laws of logarithms","Change of base","Solving logarithmic equations","Applications"]}]},{"name":"Trigonometry","topics":[{"name":"Advanced Trigonometry","subtopics":["Trigonometric identities","Compound angle formulae","Solving trig equations","Graphs of trig functions","Sine and cosine rules"]}]},{"name":"Calculus","topics":[{"name":"Differentiation","subtopics":["First principles","Rules of differentiation","Tangents and normals","Stationary points","Optimisation"]}]},{"name":"Statistics","topics":[{"name":"Probability Distributions","subtopics":["Discrete distributions","Binomial distribution","Poisson distribution","Expected value"]}]}]','{"by_end_of_year":["Work with set theory and Venn diagrams","Apply polynomial and logarithm theory","Use trigonometric identities and compound angles","Differentiate functions and find stationary points","Apply binomial and Poisson distributions"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_SHS2','GH_MATH','Mathematics','[{"name":"Pure Mathematics","topics":[{"name":"Integration","subtopics":["Rules of integration","Definite integrals","Area under a curve","Integration by substitution","Volumes of revolution"]},{"name":"Sequences and Series","subtopics":["AP and GP","Sigma notation","Sum to infinity","Binomial theorem"]},{"name":"Coordinate Geometry","subtopics":["Lines and circles","Conics introduction","Loci"]}]},{"name":"Vectors and Matrices","topics":[{"name":"Vectors","subtopics":["2D and 3D vectors","Dot product","Vector geometry proofs"]},{"name":"Matrices","subtopics":["Matrix algebra","Transformations using matrices"]}]},{"name":"Statistics","topics":[{"name":"Inference","subtopics":["Sampling distributions","Confidence intervals","Hypothesis testing","Normal distribution"]}]}]','{"by_end_of_year":["Integrate using all standard techniques","Apply binomial theorem","Work with vectors in 2D and 3D","Apply normal distribution and hypothesis testing","Use matrices for transformations"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('GH','GH_SHS3','GH_MATH','Mathematics','[{"name":"WASSCE Preparation","topics":[{"name":"Core Mathematics Revision","subtopics":["All core topics reviewed","WASSCE past paper practice","Objective test technique","Essay question technique","Common errors"]},{"name":"Elective Mathematics Extension","subtopics":["Further calculus","Differential equations","Complex numbers introduction","Numerical methods"]}]}]','{"by_end_of_year":["Revise all SHS Mathematics content","Complete WASSCE past papers under timed conditions","Apply examination technique effectively","Achieve target grade in WASSCE Mathematics"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- ══════════════════════════════════════════════
-- KENYA MATHEMATICS (CBC)
-- ══════════════════════════════════════════════

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('KE','KE_G1','KE_MATH','Mathematics','[{"name":"Numbers","topics":[{"name":"Whole Numbers","subtopics":["Counting 1 to 99","Reading and writing numbers","Comparing and ordering","Number patterns"]},{"name":"Place Value","subtopics":["Tens and ones","Grouping objects","Number lines 0-99"]}]},{"name":"Operations","topics":[{"name":"Addition and Subtraction","subtopics":["Adding within 99","Subtracting within 99","Number bonds","Word problems"]}]},{"name":"Measurement","topics":[{"name":"Length and Mass","subtopics":["Comparing lengths and heights","Comparing weights","Using non-standard units"]},{"name":"Time","subtopics":["Days of the week","Months","Morning and afternoon","Telling time to the hour"]}]},{"name":"Geometry","topics":[{"name":"Shapes","subtopics":["Identifying 2D shapes","Sorting and classifying shapes","Patterns"]}]}]','{"by_end_of_year":["Count, read and write numbers to 99","Add and subtract within 99","Identify basic 2D shapes","Tell time to the hour","Compare lengths and weights"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('KE','KE_G2','KE_MATH','Mathematics','[{"name":"Numbers","topics":[{"name":"Whole Numbers to 999","subtopics":["Hundreds, tens and ones","Reading and writing numbers","Comparing using < > =","Ordering numbers"]},{"name":"Fractions","subtopics":["Half and quarter of a whole","Half and quarter of a set"]}]},{"name":"Operations","topics":[{"name":"Addition and Subtraction","subtopics":["Adding 3-digit numbers","Subtracting 3-digit numbers","Carrying and borrowing","Word problems"]},{"name":"Multiplication","subtopics":["Repeated addition","2, 5 and 10 times tables","Multiplication as arrays"]},{"name":"Division","subtopics":["Sharing equally","Dividing by 2, 5 and 10"]}]},{"name":"Measurement","topics":[{"name":"Length","subtopics":["Centimetres and metres","Measuring objects","Comparing lengths"]},{"name":"Money","subtopics":["Kenyan coins and notes","Adding money","Shopping problems"]}]},{"name":"Geometry","topics":[{"name":"Shapes","subtopics":["Properties of 2D shapes","3D shapes: cubes, cuboids, spheres","Symmetry"]}]}]','{"by_end_of_year":["Read and write numbers to 999","Know 2, 5 and 10 times tables","Add and subtract 3-digit numbers","Use Kenyan currency","Identify 3D shapes"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('KE','KE_G3','KE_MATH','Mathematics','[{"name":"Numbers","topics":[{"name":"Numbers to 9999","subtopics":["Place value to thousands","Rounding","LCM and HCF"]},{"name":"Fractions","subtopics":["Equivalent fractions","Comparing fractions","Fractions of quantities"]}]},{"name":"Operations","topics":[{"name":"All Operations","subtopics":["Times tables 1 to 10","Multiplying 2-digit by 1-digit","Dividing 2-digit by 1-digit","BODMAS introduction","Word problems"]}]},{"name":"Measurement","topics":[{"name":"Perimeter and Area","subtopics":["Perimeter of rectangles","Area by counting squares"]},{"name":"Mass and Capacity","subtopics":["Kilograms and grams","Litres and millilitres"]}]},{"name":"Geometry","topics":[{"name":"Angles and Shapes","subtopics":["Right angles","Types of triangles","Quadrilaterals"]}]},{"name":"Data Handling","topics":[{"name":"Graphs","subtopics":["Bar charts","Pictograms","Tally charts","Mode"]}]}]','{"by_end_of_year":["Know all times tables to 10","Add and subtract 4-digit numbers","Find equivalent fractions","Calculate perimeter and area","Read and draw bar charts"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('KE','KE_G4','KE_MATH','Mathematics','[{"name":"Numbers","topics":[{"name":"Numbers to 100,000","subtopics":["Place value","Factors and multiples","Square numbers","LCM and HCF"]},{"name":"Fractions and Decimals","subtopics":["All operations with fractions","Decimal notation","Percentage"]}]},{"name":"Operations","topics":[{"name":"Multiplication and Division","subtopics":["Multiplying 3-digit by 2-digit","Long division","Order of operations","Financial mathematics"]}]},{"name":"Measurement","topics":[{"name":"Area and Volume","subtopics":["Area of rectangles and triangles","Volume of cuboids"]},{"name":"Time","subtopics":["24-hour clock","Time intervals","Timetables"]}]},{"name":"Geometry","topics":[{"name":"Angles","subtopics":["Measuring angles","Angles in triangles","Coordinates"]}]},{"name":"Data and Probability","topics":[{"name":"Statistics","subtopics":["Mean, median, mode","Frequency tables","Line graphs"]},{"name":"Probability","subtopics":["Simple probability","Sample space"]}]}]','{"by_end_of_year":["Work with numbers to 100,000","Multiply 3-digit by 2-digit","Calculate percentage","Find area and volume","Use 24-hour clock"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('KE','KE_G5','KE_MATH','Mathematics','[{"name":"Numbers","topics":[{"name":"Large Numbers","subtopics":["Numbers to 1,000,000","Prime factorisation","Squares and square roots","Cubes","Index notation"]},{"name":"Fractions, Decimals, Percentages","subtopics":["All operations","Converting between forms","Profit and loss","Simple interest"]}]},{"name":"Algebra","topics":[{"name":"Algebra","subtopics":["Expressions","Simple equations","Sequences and patterns"]}]},{"name":"Measurement","topics":[{"name":"Area and Volume","subtopics":["Area of composite shapes","Volume of prisms","Surface area"]},{"name":"Ratio and Proportion","subtopics":["Ratio","Direct proportion","Scale drawings"]}]},{"name":"Geometry","topics":[{"name":"Shapes and Transformations","subtopics":["Circle: circumference and area","Constructions","Reflection, rotation, translation"]}]},{"name":"Statistics","topics":[{"name":"Data Handling","subtopics":["Pie charts","Histograms","Probability: combined events"]}]}]','{"by_end_of_year":["Work with numbers to 1,000,000","Calculate profit, loss and simple interest","Solve algebraic equations","Calculate circumference and area of circles","Apply ratio and proportion"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('KE','KE_G6','KE_MATH','Mathematics','[{"name":"Numbers and Algebra","topics":[{"name":"Number Theory","subtopics":["Standard form","Significant figures","Rational numbers"]},{"name":"Algebra","subtopics":["Expanding and factorising","Linear equations","Simultaneous equations","Sequences"]}]},{"name":"Geometry","topics":[{"name":"Plane Geometry","subtopics":["Angles in parallel lines","Pythagoras theorem","Circle theorems introduction"]},{"name":"Mensuration","subtopics":["Area and perimeter of all shapes","Volume of all common solids","Surface area"]}]},{"name":"Statistics","topics":[{"name":"Data Analysis","subtopics":["Cumulative frequency","Standard deviation","Probability: tree diagrams","Combined events"]}]}]','{"by_end_of_year":["Apply Pythagoras theorem","Solve simultaneous equations","Calculate surface area and volume of all 3D shapes","Interpret cumulative frequency","Apply probability using tree diagrams"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('KE','KE_G7','KE_MATH','Mathematics','[{"name":"Number","topics":[{"name":"Number Bases and Directed Numbers","subtopics":["Binary and other bases","Operations with directed numbers","Standard form","Indices"]},{"name":"Fractions and Percentages","subtopics":["Compound interest","Depreciation","Tax calculations","Hire purchase"]}]},{"name":"Algebra","topics":[{"name":"Quadratics and Functions","subtopics":["Quadratic equations","Graphical solutions","Functions and mappings","Linear programming"]}]},{"name":"Geometry","topics":[{"name":"Trigonometry","subtopics":["Sin, cos, tan","Angles of elevation and depression","Bearings","3D trigonometry"]},{"name":"Transformations","subtopics":["All transformations","Matrix representation"]}]},{"name":"Statistics","topics":[{"name":"Statistics","subtopics":["Frequency distributions","Measures of spread","Regression","Probability distributions"]}]}]','{"by_end_of_year":["Solve quadratic equations","Apply trigonometry in 2D and 3D","Use linear programming","Apply compound interest and depreciation","Interpret statistical distributions"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('KE','KE_G8','KE_MATH','Mathematics','[{"name":"Pure Mathematics","topics":[{"name":"Algebra","subtopics":["Polynomials","Remainder and factor theorems","Partial fractions","Matrices and determinants"]},{"name":"Calculus","subtopics":["Differentiation from first principles","Rules of differentiation","Integration","Applications: area, stationary points"]}]},{"name":"Trigonometry","topics":[{"name":"Advanced Trigonometry","subtopics":["Identities","Compound angles","Sine and cosine rules","Graphs of trig functions"]}]},{"name":"Coordinate Geometry","topics":[{"name":"Coordinate Geometry","subtopics":["Straight lines","Circles","Conics: parabola, ellipse"]}]},{"name":"Statistics","topics":[{"name":"Statistical Inference","subtopics":["Normal distribution","Hypothesis testing","Binomial distribution"]}]}]','{"by_end_of_year":["Differentiate and integrate polynomial functions","Apply polynomial theorems","Use matrix algebra","Apply advanced trigonometric identities","Conduct statistical hypothesis tests"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('KE','KE_G9','KE_MATH','Mathematics','[{"name":"Advanced Pure Mathematics","topics":[{"name":"Further Calculus","subtopics":["Chain, product and quotient rules","Integration by substitution and parts","Differential equations","Series: AP, GP, binomial"]},{"name":"Further Algebra","subtopics":["Complex numbers","Sequences","Mathematical induction"]}]},{"name":"Vectors and Mechanics","topics":[{"name":"Vectors","subtopics":["3D vectors","Scalar and vector products","Vector equations of lines and planes"]},{"name":"Mechanics","subtopics":["Kinematics: SUVAT","Forces and Newton laws","Projectiles","Moments"]}]},{"name":"KCSE Preparation","topics":[{"name":"Exam Preparation","subtopics":["KCSE past papers","Paper 1 and Paper 2 techniques","Time management","Common errors"]}]}]','{"by_end_of_year":["Apply advanced calculus techniques","Work with complex numbers","Apply vector geometry in 3D","Solve mechanics problems","Prepare for KCSE Mathematics examinations"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
select 'KE',yg.year_group_code,'KE_MATH','Mathematics',
'[{"name":"Senior Secondary Mathematics","topics":[{"name":"Pure Mathematics","subtopics":["Comprehensive algebra and calculus","Trigonometry and coordinate geometry","Series and sequences","Vectors and matrices"]},{"name":"Statistics and Mechanics","subtopics":["Probability distributions","Statistical inference","Kinematics and dynamics","KCSE examination preparation"]}]}]',
'{"by_end_of_year":["Complete all KCSE Mathematics content","Apply mathematical skills to real-world problems","Achieve target grade in KCSE"]}'
from year_group_equivalencies yg
where yg.country_code='KE' and yg.stage='senior_secondary'
on conflict (country_code,year_group_code,subject_code) do nothing;

-- ══════════════════════════════════════════════
-- SOUTH AFRICA MATHEMATICS (CAPS)
-- ══════════════════════════════════════════════

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('ZA','ZA_G1','ZA_MATH','Mathematics','[{"name":"Numbers, Operations and Relationships","topics":[{"name":"Whole Numbers","subtopics":["Counting to 100","Reading and writing numbers","Ordering and comparing","Number bonds to 10 and 20","Adding and subtracting within 20"]},{"name":"Fractions","subtopics":["Halves and quarters of objects and shapes"]}]},{"name":"Patterns, Functions and Algebra","topics":[{"name":"Patterns","subtopics":["Geometric patterns","Number patterns: counting in 2s, 5s, 10s"]}]},{"name":"Space and Shape","topics":[{"name":"2D Shapes","subtopics":["Circles, triangles, squares, rectangles","Sorting and describing shapes"]},{"name":"3D Objects","subtopics":["Balls, boxes, cylinders","Sorting and describing"]}]},{"name":"Measurement","topics":[{"name":"Informal Measurement","subtopics":["Length: longer, shorter","Mass: heavier, lighter","Capacity: more, less","Time: before, after, days of week"]}]},{"name":"Data Handling","topics":[{"name":"Data","subtopics":["Sorting objects","Pictographs","Answering questions about data"]}]}]','{"by_end_of_year":["Count to 100","Add and subtract within 20","Identify basic 2D shapes and 3D objects","Compare lengths, masses and capacities","Read simple pictographs"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('ZA','ZA_G2','ZA_MATH','Mathematics','[{"name":"Numbers, Operations and Relationships","topics":[{"name":"Whole Numbers","subtopics":["Numbers to 200","Place value: hundreds, tens, ones","Addition and subtraction within 200","Multiplication: 2, 5, 10 times tables","Division: sharing and grouping"]},{"name":"Fractions","subtopics":["Halves, quarters and thirds"]}]},{"name":"Patterns, Functions and Algebra","topics":[{"name":"Patterns","subtopics":["Geometric patterns","Number patterns","Skip counting in 3s, 4s"]}]},{"name":"Space and Shape","topics":[{"name":"Shapes","subtopics":["Properties of 2D shapes","Properties of 3D objects","Symmetry","Position and directions"]}]},{"name":"Measurement","topics":[{"name":"Measurement","subtopics":["Centimetres and metres","Grams and kilograms","Millilitres and litres","Time: hours, half hours, quarter hours","South African money"]}]},{"name":"Data Handling","topics":[{"name":"Data","subtopics":["Tally marks","Pictographs","Bar graphs"]}]}]','{"by_end_of_year":["Work with numbers to 200","Know 2, 5 and 10 times tables","Identify properties of 2D and 3D shapes","Measure in cm, m, g, kg, ml, l","Use South African money"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('ZA','ZA_G3','ZA_MATH','Mathematics','[{"name":"Numbers, Operations and Relationships","topics":[{"name":"Whole Numbers","subtopics":["Numbers to 999","All four operations","Times tables to 10","Division with remainders"]},{"name":"Fractions","subtopics":["Proper fractions","Equivalent fractions","Fractions of whole numbers"]}]},{"name":"Patterns, Functions and Algebra","topics":[{"name":"Patterns","subtopics":["Number patterns","Input-output tables","Geometric patterns"]}]},{"name":"Space and Shape","topics":[{"name":"Geometry","subtopics":["2D shapes: sides, angles, vertices","3D objects: faces, edges","Transformations: flip, slide, turn","Views of objects"]}]},{"name":"Measurement","topics":[{"name":"Measurement","subtopics":["Perimeter","Area by counting","Mass, capacity and length","Time: minutes, 24-hour clock introduction","Money: calculating change"]}]},{"name":"Data Handling","topics":[{"name":"Data","subtopics":["Collecting data","Bar graphs","Pie charts introduction","Mode"]}]}]','{"by_end_of_year":["Know all times tables to 10","Work with numbers to 999","Find equivalent fractions","Calculate perimeter and area","Read bar graphs and pie charts"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('ZA','ZA_G4','ZA_MATH','Mathematics','[{"name":"Numbers, Operations and Relationships","topics":[{"name":"Whole Numbers","subtopics":["Numbers to 99,999","Factors and multiples","LCM and HCF","Properties of operations"]},{"name":"Common Fractions","subtopics":["Equivalent fractions","Adding and subtracting fractions","Mixed numbers"]},{"name":"Decimal Fractions","subtopics":["Tenths and hundredths","Decimal notation","Rounding"]}]},{"name":"Patterns, Functions and Algebra","topics":[{"name":"Numeric Patterns","subtopics":["Sequences","Geometric patterns","Input-output tables","Equations with variables"]}]},{"name":"Space and Shape","topics":[{"name":"Geometry","subtopics":["Properties of 2D shapes","Properties of 3D objects","Congruency","Transformations","Coordinates"]}]},{"name":"Measurement","topics":[{"name":"Measurement","subtopics":["Perimeter and area of rectangles","Volume of cuboids","Time: elapsed time","Converting units"]}]},{"name":"Data Handling","topics":[{"name":"Data","subtopics":["Collecting and organising data","Bar graphs","Pie charts","Mean, median, mode"]}]}]','{"by_end_of_year":["Work with numbers to 99,999","Add and subtract fractions","Understand decimal fractions","Calculate perimeter, area and volume","Find mean, median and mode"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('ZA','ZA_G5','ZA_MATH','Mathematics','[{"name":"Numbers, Operations and Relationships","topics":[{"name":"Whole Numbers","subtopics":["Numbers to 999,999","Prime numbers","Square numbers","Exponents"]},{"name":"Fractions","subtopics":["Multiplying fractions","Dividing fractions","Percentages","Ratio and rate"]},{"name":"Decimal Fractions","subtopics":["Thousandths","Operations with decimals","Rounding"]}]},{"name":"Patterns, Functions and Algebra","topics":[{"name":"Algebra","subtopics":["Variables","Equations","Graphs: plotting and reading","Flow diagrams"]}]},{"name":"Space and Shape","topics":[{"name":"Geometry","subtopics":["Angles: types and measurement","Properties of triangles and quadrilaterals","Circles","Transformations: all types"]}]},{"name":"Measurement","topics":[{"name":"Measurement","subtopics":["Area of triangles and parallelograms","Volume of prisms","Temperature","Converting between units"]}]},{"name":"Data Handling and Probability","topics":[{"name":"Data","subtopics":["Histograms","Scatter plots","Mean from frequency tables"]},{"name":"Probability","subtopics":["Probability scale","Equally likely outcomes","Experimental probability"]}]}]','{"by_end_of_year":["Work with numbers to 999,999","Multiply and divide fractions","Calculate percentages and ratios","Find area of triangles and parallelograms","Apply basic probability"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('ZA','ZA_G6','ZA_MATH','Mathematics','[{"name":"Numbers, Operations and Relationships","topics":[{"name":"Whole Numbers and Integers","subtopics":["Directed numbers","Prime factorisation","LCM and HCF","Standard form"]},{"name":"Fractions, Decimals and Percentages","subtopics":["Financial mathematics: profit, loss, interest, VAT","Ratio and proportion"]}]},{"name":"Patterns, Functions and Algebra","topics":[{"name":"Algebra","subtopics":["Algebraic expressions","Equations","Inequalities","Graphs of functions"]}]},{"name":"Space and Shape","topics":[{"name":"Geometry","subtopics":["Angle relationships in parallel lines","Pythagoras theorem","Circle: circumference and area","Constructions"]}]},{"name":"Measurement","topics":[{"name":"Measurement","subtopics":["Surface area and volume of all prisms","Cylinders"]}]},{"name":"Data Handling and Probability","topics":[{"name":"Statistics","subtopics":["Frequency distributions","Box and whisker plots","Variance and standard deviation"]},{"name":"Probability","subtopics":["Tree diagrams","Combined events","Mutually exclusive events"]}]}]','{"by_end_of_year":["Apply Pythagoras theorem","Solve algebraic equations and inequalities","Calculate circumference and area of circles","Find surface area and volume of prisms and cylinders","Calculate standard deviation"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('ZA','ZA_G7','ZA_MATH','Mathematics','[{"name":"Numbers and Algebra","topics":[{"name":"Number Patterns and Sequences","subtopics":["Quadratic sequences","Geometric sequences","Sigma notation"]},{"name":"Functions","subtopics":["Linear functions","Quadratic functions","Hyperbola","Exponential functions","Graphs and transformations"]}]},{"name":"Algebra","topics":[{"name":"Algebraic Expressions","subtopics":["Products and factorisation","Algebraic fractions","Equations: linear, quadratic, simultaneous"]},{"name":"Finance","subtopics":["Simple and compound interest","Annuities","Present and future value"]}]},{"name":"Trigonometry","topics":[{"name":"Trigonometry","subtopics":["Trig ratios","Reduction formulae","Trig equations","Sine and cosine rules"]}]},{"name":"Geometry","topics":[{"name":"Analytical Geometry","subtopics":["Distance formula","Midpoint formula","Gradient","Equation of a line","Equation of a circle"]},{"name":"Euclidean Geometry","subtopics":["Circle theorems","Proofs"]}]},{"name":"Statistics and Probability","topics":[{"name":"Statistics","subtopics":["Ogives","Histograms","Regression"]},{"name":"Probability","subtopics":["Counting principles","Permutations","Combinations","Conditional probability"]}]}]','{"by_end_of_year":["Work with all function types and their graphs","Solve quadratic and simultaneous equations","Apply all trig identities and rules","Apply Euclidean geometry theorems","Apply counting principles and conditional probability"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('ZA','ZA_G8','ZA_MATH','Mathematics','[{"name":"FET Phase Mathematics","topics":[{"name":"Calculus","subtopics":["Limits and continuity","Rules of differentiation","Applications of differentiation","Integration","Area under a curve"]},{"name":"Linear Programming","subtopics":["Feasible region","Optimisation"]},{"name":"Further Algebra","subtopics":["Polynomials","Remainder and factor theorems"]}]},{"name":"Trigonometry and Geometry","topics":[{"name":"Advanced Topics","subtopics":["Compound angles","Double angles","3D trigonometry","Further Euclidean geometry proofs"]}]},{"name":"Statistics","topics":[{"name":"Advanced Statistics","subtopics":["Normal distribution","Hypothesis testing","Bivariate data"]}]}]','{"by_end_of_year":["Differentiate and integrate polynomial functions","Apply linear programming","Work with compound and double angles","Apply normal distribution","Complete Grade 11 CAPS content"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies) values
('ZA','ZA_G9','ZA_MATH','Mathematics','[{"name":"Grade 12 CAPS Revision and Examination","topics":[{"name":"Full Revision","subtopics":["All Grade 10, 11 and 12 topics","NSC past paper practice","Paper 1 and Paper 2 technique","Time management","Common errors"]},{"name":"Grade 12 Extension","subtopics":["Further calculus applications","Advanced statistics","Proof in Euclidean geometry"]}]}]','{"by_end_of_year":["Revise all CAPS Mathematics content","Complete NSC past papers under timed conditions","Apply examination technique","Achieve target grade in NSC Mathematics (Matric)"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
select 'ZA',yg.year_group_code,'ZA_MATH','Mathematics',
'[{"name":"NSC Senior Secondary Mathematics","topics":[{"name":"Algebra, Functions and Calculus","subtopics":["All function types","Differentiation and integration","Applications"]},{"name":"Trigonometry and Geometry","subtopics":["Advanced trigonometry","Euclidean geometry proofs","Analytical geometry"]},{"name":"Statistics and Probability","subtopics":["Normal distribution","Counting principles","NSC examination preparation"]}]}]',
'{"by_end_of_year":["Complete all NSC Mathematics content","Prepare for National Senior Certificate examinations"]}'
from year_group_equivalencies yg
where yg.country_code='ZA' and yg.stage='senior_secondary'
on conflict (country_code,year_group_code,subject_code) do nothing;
