
-- ══════════════════════════════════════════════
-- NIGERIA MATHEMATICS — CORRECT COLUMN NAMES
-- ══════════════════════════════════════════════

-- NG Primary 1
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_P1','NG_MATH','Mathematics',
'[{"name":"Numbers and Numeration","topics":[{"name":"Counting and Writing Numbers","subtopics":["Counting 1 to 100","Writing numbers in words and figures","Ordering numbers","Odd and even numbers"]},{"name":"Place Value","subtopics":["Ones and tens","Grouping in tens","Expanded notation"]},{"name":"Fractions","subtopics":["Half and quarter of a whole","Half and quarter of a set"]}]},{"name":"Basic Operations","topics":[{"name":"Addition","subtopics":["Adding numbers up to 99","Adding with carrying","Number bonds to 20"]},{"name":"Subtraction","subtopics":["Subtracting numbers up to 99","Subtraction with borrowing","Difference between numbers"]}]},{"name":"Measurement","topics":[{"name":"Length","subtopics":["Comparing lengths","Measuring with non-standard units","Introduction to rulers"]},{"name":"Weight","subtopics":["Heavier and lighter","Comparing weights"]},{"name":"Time","subtopics":["Days of the week","Months of the year","Telling time to the hour"]}]},{"name":"Geometry","topics":[{"name":"Shapes","subtopics":["Identifying circles, squares, triangles, rectangles","Properties of 2D shapes","Sorting shapes"]}]}]',
'{"by_end_of_year":["Count, read and write numbers to 100","Add and subtract numbers up to 99","Identify basic 2D shapes","Measure length and weight using non-standard units","Tell time to the hour"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG Primary 2
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_P2','NG_MATH','Mathematics',
'[{"name":"Numbers and Numeration","topics":[{"name":"Numbers to 999","subtopics":["Reading and writing numbers to 999","Place value: ones, tens, hundreds","Comparing and ordering numbers","Roman numerals I to X"]},{"name":"Fractions","subtopics":["Halves, quarters, thirds","Equivalent fractions","Fractions of a set"]}]},{"name":"Basic Operations","topics":[{"name":"Addition","subtopics":["Adding 3-digit numbers","Adding with carrying","Word problems"]},{"name":"Subtraction","subtopics":["Subtracting 3-digit numbers","Borrowing across zeros","Word problems"]},{"name":"Multiplication","subtopics":["Multiplication as repeated addition","2, 3, 4, 5 times tables","Multiplying by 10"]},{"name":"Division","subtopics":["Division as sharing equally","Dividing by 2, 3, 4, 5","Relationship between multiplication and division"]}]},{"name":"Measurement","topics":[{"name":"Length","subtopics":["Measuring in centimetres and metres","Comparing lengths","Perimeter of simple shapes"]},{"name":"Capacity","subtopics":["Litres and millilitres","Comparing capacities"]},{"name":"Time","subtopics":["Telling time to the half hour","Days, weeks, months","Simple timetables"]}]},{"name":"Money","topics":[{"name":"Nigerian Currency","subtopics":["Identifying naira and kobo notes and coins","Adding and subtracting amounts","Shopping problems"]}]},{"name":"Geometry","topics":[{"name":"2D and 3D Shapes","subtopics":["Properties of triangles, squares, rectangles, circles","Cubes, cuboids, spheres, cylinders","Lines of symmetry"]}]}]',
'{"by_end_of_year":["Read and write numbers to 999","Know times tables for 2,3,4,5","Add and subtract 3-digit numbers","Identify and use Nigerian currency","Measure in cm and m"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG Primary 3
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_P3','NG_MATH','Mathematics',
'[{"name":"Numbers and Numeration","topics":[{"name":"Numbers to 9,999","subtopics":["Reading, writing, ordering numbers to 9999","Place value to thousands","Rounding to nearest 10 and 100","Roman numerals to XX"]},{"name":"Fractions and Decimals","subtopics":["Proper and improper fractions","Mixed numbers","Comparing fractions","Decimal notation for tenths"]}]},{"name":"Operations","topics":[{"name":"Multiplication","subtopics":["Times tables 1 to 10","Multiplying 2-digit by 1-digit","Multiplying by multiples of 10"]},{"name":"Division","subtopics":["Dividing 2-digit by 1-digit","Remainders","Long division introduction"]},{"name":"Word Problems","subtopics":["Multi-step problems","Choosing correct operation","Estimation"]}]},{"name":"Measurement","topics":[{"name":"Length and Perimeter","subtopics":["Kilometres, metres, centimetres","Perimeter of rectangles and triangles"]},{"name":"Area","subtopics":["Area by counting squares","Area of rectangles"]},{"name":"Mass and Capacity","subtopics":["Kilograms and grams","Litres and millilitres","Conversion between units"]}]},{"name":"Geometry","topics":[{"name":"Angles","subtopics":["Right angles","Acute and obtuse angles","Angles on a straight line"]},{"name":"Shapes","subtopics":["Quadrilaterals","Types of triangles","3D shapes and nets"]}]},{"name":"Data Handling","topics":[{"name":"Statistics","subtopics":["Reading and drawing bar charts","Pictograms","Tally charts","Mode and range"]}]}]',
'{"by_end_of_year":["Know all times tables to 10","Multiply and divide 2-digit numbers","Understand fractions and decimals to tenths","Calculate perimeter and area of rectangles","Read and draw bar charts"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG Primary 4
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_P4','NG_MATH','Mathematics',
'[{"name":"Numbers and Numeration","topics":[{"name":"Numbers to 99,999","subtopics":["Reading and writing large numbers","Place value to ten-thousands","Comparing and ordering","Factors and multiples","LCM and HCF"]},{"name":"Fractions","subtopics":["Adding and subtracting fractions with same denominator","Equivalent fractions","Fractions of quantities"]},{"name":"Decimals","subtopics":["Tenths and hundredths","Adding and subtracting decimals","Rounding decimals"]}]},{"name":"Operations","topics":[{"name":"Multiplication","subtopics":["Multiplying 3-digit by 2-digit","Multiplying decimals by 10 and 100","Word problems"]},{"name":"Division","subtopics":["Dividing 3-digit by 1-digit","Division with remainders","Checking with multiplication"]}]},{"name":"Measurement","topics":[{"name":"Length, Mass and Capacity","subtopics":["Converting between units","Solving measurement problems"]},{"name":"Area and Perimeter","subtopics":["Area of compound shapes","Perimeter of irregular shapes"]},{"name":"Time","subtopics":["24-hour clock","Calculating duration","Time zones introduction"]}]},{"name":"Geometry","topics":[{"name":"Angles","subtopics":["Measuring angles with a protractor","Angles in a triangle sum to 180","Vertically opposite angles"]},{"name":"Coordinates","subtopics":["First quadrant coordinates","Plotting and reading coordinates","Simple maps"]}]},{"name":"Data Handling","topics":[{"name":"Statistics","subtopics":["Mean, median, mode","Frequency tables","Line graphs","Pie charts introduction"]}]}]',
'{"by_end_of_year":["Work with numbers to 99,999","Add and subtract fractions with same denominator","Multiply 3-digit by 2-digit numbers","Measure and calculate area of compound shapes","Calculate mean, median and mode"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG Primary 5
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_P5','NG_MATH','Mathematics',
'[{"name":"Numbers and Numeration","topics":[{"name":"Numbers to 1,000,000","subtopics":["Millions, hundred-thousands","Prime and composite numbers","Prime factorisation","Square and square roots","Index notation"]},{"name":"Fractions, Decimals and Percentages","subtopics":["Adding and subtracting unlike fractions","Multiplying fractions","Percentage of a quantity","Converting between fractions, decimals and percentages"]}]},{"name":"Operations","topics":[{"name":"Multiplication and Division","subtopics":["Long multiplication","Long division","Order of operations (BODMAS)","Word problems with multiple steps"]}]},{"name":"Algebra","topics":[{"name":"Introduction to Algebra","subtopics":["Using letters for unknowns","Simple equations","Number patterns and sequences"]}]},{"name":"Geometry","topics":[{"name":"Angles and Shapes","subtopics":["Angles in polygons","Properties of circles","Constructions with compass and ruler"]},{"name":"Coordinates","subtopics":["Four quadrants","Reflection and translation","Simple transformations"]}]},{"name":"Measurement","topics":[{"name":"Volume and Surface Area","subtopics":["Volume of cuboids","Surface area of cuboids","Real-life applications"]}]},{"name":"Data Handling","topics":[{"name":"Statistics and Probability","subtopics":["Frequency distributions","Histograms","Probability: likely, unlikely, certain, impossible","Simple probability fractions"]}]}]',
'{"by_end_of_year":["Work with numbers to 1,000,000","Multiply and divide fractions","Use BODMAS correctly","Solve simple algebraic equations","Calculate volume of cuboids","Understand basic probability"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG Primary 6
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_P6','NG_MATH','Mathematics',
'[{"name":"Numbers and Numeration","topics":[{"name":"Number Theory","subtopics":["LCM and HCF of large numbers","Rational and irrational numbers introduction","Standard form","Significant figures","Estimation and approximation"]},{"name":"Ratios and Proportions","subtopics":["Simplifying ratios","Dividing quantities in a ratio","Direct and inverse proportion","Map scales"]}]},{"name":"Operations and Algebra","topics":[{"name":"Algebra","subtopics":["Expanding brackets","Factorising simple expressions","Solving linear equations","Substitution into formulae"]},{"name":"Word Problems","subtopics":["Profit and loss","Simple interest","Hire purchase","Commission and discount"]}]},{"name":"Geometry","topics":[{"name":"Plane Geometry","subtopics":["Angles in parallel lines","Pythagoras theorem introduction","Properties of polygons","Circle: radius, diameter, circumference"]},{"name":"Mensuration","subtopics":["Area of triangles and parallelograms","Circumference and area of circles","Volume of prisms"]}]},{"name":"Data Handling","topics":[{"name":"Statistics","subtopics":["Mean from frequency tables","Cumulative frequency","Interpreting graphs","Misleading statistics"]},{"name":"Probability","subtopics":["Sample space","Theoretical probability","Experimental probability","Mutually exclusive events"]}]}]',
'{"by_end_of_year":["Apply ratio and proportion to real-life problems","Expand and factorise simple algebraic expressions","Calculate circumference and area of circles","Apply Pythagoras theorem to simple problems","Interpret statistical graphs and calculate probability"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG JSS 1
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_JSS1','NG_MATH','Mathematics',
'[{"name":"Number and Numeration","topics":[{"name":"Whole Numbers","subtopics":["Place value to billions","Operations with large numbers","LCM and HCF","Prime factorisation"]},{"name":"Fractions, Decimals and Percentages","subtopics":["All operations with fractions","Converting between forms","Percentage increase and decrease","Reverse percentage"]}]},{"name":"Algebraic Processes","topics":[{"name":"Algebra","subtopics":["Collecting like terms","Expanding single brackets","Solving linear equations","Formulae and substitution","Sequences: nth term"]},{"name":"Word Problems","subtopics":["Setting up equations","Financial mathematics","Rate, speed, distance, time"]}]},{"name":"Geometry and Mensuration","topics":[{"name":"Angles","subtopics":["Angles at a point","Angles on a straight line","Angles in triangles and quadrilaterals","Bearings introduction"]},{"name":"Plane Shapes","subtopics":["Area of composite shapes","Perimeter","Circle: arc, sector, chord"]},{"name":"Solid Shapes","subtopics":["Surface area of cubes and cuboids","Volume of cubes and cuboids","Cross-sections"]}]},{"name":"Statistics","topics":[{"name":"Data Collection and Presentation","subtopics":["Frequency tables","Bar charts, histograms, pie charts","Mean, median, mode from grouped data","Interpretation of graphs"]}]}]',
'{"by_end_of_year":["Perform all operations with fractions and percentages","Solve linear equations and use formulae","Calculate angles in geometric figures","Find area and volume of standard shapes","Interpret statistical charts and calculate averages"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG JSS 2
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_JSS2','NG_MATH','Mathematics',
'[{"name":"Number and Numeration","topics":[{"name":"Number Bases","subtopics":["Base 2 (binary)","Base 8 (octal)","Converting between bases","Operations in different bases"]},{"name":"Rational Numbers","subtopics":["Integers on a number line","Operations with directed numbers","Standard form and scientific notation"]}]},{"name":"Algebraic Processes","topics":[{"name":"Simultaneous Equations","subtopics":["Solving by substitution","Solving by elimination","Word problems leading to simultaneous equations"]},{"name":"Inequalities","subtopics":["Solving linear inequalities","Graphing inequalities on a number line","Combined inequalities"]}]},{"name":"Geometry","topics":[{"name":"Pythagoras Theorem","subtopics":["Deriving Pythagoras theorem","Finding missing sides","Real-life applications","Pythagorean triples"]},{"name":"Trigonometry Introduction","subtopics":["Sine, cosine, tangent ratios","Finding angles and sides in right triangles"]},{"name":"Transformation","subtopics":["Reflection","Rotation","Translation","Enlargement"]}]},{"name":"Statistics and Probability","topics":[{"name":"Probability","subtopics":["Addition rule","Multiplication rule","Tree diagrams","Relative frequency"]}]}]',
'{"by_end_of_year":["Convert between number bases","Solve simultaneous linear equations","Apply Pythagoras theorem","Use basic trigonometric ratios","Apply probability rules and tree diagrams"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG JSS 3
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_JSS3','NG_MATH','Mathematics',
'[{"name":"Number and Numeration","topics":[{"name":"Surds","subtopics":["Definition of surds","Simplifying surds","Operations with surds","Rationalising the denominator"]},{"name":"Indices","subtopics":["Laws of indices","Negative and fractional indices","Exponential equations"]}]},{"name":"Algebraic Processes","topics":[{"name":"Factorisation","subtopics":["Factorising quadratics","Difference of two squares","Perfect square trinomials"]},{"name":"Quadratic Equations","subtopics":["Solving by factorisation","Solving by completing the square","Quadratic formula","Nature of roots"]},{"name":"Graphs","subtopics":["Cartesian plane","Straight line graphs","Gradient and intercept","Quadratic curves"]}]},{"name":"Geometry","topics":[{"name":"Circle Theorems","subtopics":["Angle in a semicircle","Angles in the same segment","Cyclic quadrilaterals","Tangent-radius theorem"]},{"name":"Mensuration","subtopics":["Arc length and sector area","Volume of spheres, cones, cylinders","Surface area of spheres and cones"]}]},{"name":"Statistics","topics":[{"name":"Cumulative Frequency","subtopics":["Ogive","Median, quartiles from ogive","Box and whisker plots","Interquartile range"]}]}]',
'{"by_end_of_year":["Work with surds and indices","Solve quadratic equations by all methods","Apply circle theorems","Calculate arc length, sector area, and volumes of 3D shapes","Construct and interpret cumulative frequency graphs"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG SS 1
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_SS1','NG_MATH','Mathematics',
'[{"name":"Number and Numeration","topics":[{"name":"Logarithms","subtopics":["Laws of logarithms","Common logarithm tables","Antilogarithm","Applications of logarithms"]},{"name":"Sets","subtopics":["Set notation","Subsets","Union and intersection","Complement","Venn diagrams with three sets","Real-life applications of sets"]}]},{"name":"Algebraic Processes","topics":[{"name":"Polynomials","subtopics":["Operations on polynomials","Remainder theorem","Factor theorem","Polynomial equations"]},{"name":"Matrices","subtopics":["Matrix notation","Addition and subtraction","Multiplication","Determinant of 2x2 matrix","Inverse of 2x2 matrix"]},{"name":"Linear Programming","subtopics":["Feasible region","Objective function","Maximising and minimising","Real-life applications"]}]},{"name":"Trigonometry","topics":[{"name":"Trigonometric Ratios","subtopics":["Sine, cosine, tangent for all angles","Unit circle","Graphs of trig functions","Trig identities","Solving trig equations"]}]},{"name":"Calculus Introduction","topics":[{"name":"Differentiation","subtopics":["Concept of a limit","Differentiation from first principles","Rules of differentiation","Gradient of curves","Stationary points"]}]}]',
'{"by_end_of_year":["Use logarithm tables and laws","Solve problems using Venn diagrams","Perform matrix operations","Apply linear programming","Differentiate polynomial functions and find stationary points"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG SS 2
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_SS2','NG_MATH','Mathematics',
'[{"name":"Calculus","topics":[{"name":"Differentiation","subtopics":["Chain rule","Product rule","Quotient rule","Applications: velocity, acceleration","Maximum and minimum problems"]},{"name":"Integration","subtopics":["Antiderivatives","Indefinite integrals","Definite integrals","Area under a curve","Volumes of revolution"]}]},{"name":"Statistics and Probability","topics":[{"name":"Statistics","subtopics":["Frequency distribution","Mean, median, mode from grouped data","Standard deviation","Variance","Normal distribution introduction"]},{"name":"Probability","subtopics":["Independent and dependent events","Conditional probability","Binomial probability","Expected value"]}]},{"name":"Coordinate Geometry","topics":[{"name":"Straight Lines","subtopics":["Distance between two points","Midpoint formula","Gradient","Equation of a line","Parallel and perpendicular lines"]},{"name":"Circles","subtopics":["Equation of a circle","Centre and radius","Tangent to a circle","Intersection of lines and circles"]}]},{"name":"Vectors","topics":[{"name":"Vectors in 2D","subtopics":["Vector notation","Addition and subtraction","Scalar multiplication","Unit vectors","Position vectors","Dot product"]}]}]',
'{"by_end_of_year":["Differentiate using chain, product and quotient rules","Integrate and find areas under curves","Calculate standard deviation and variance","Apply coordinate geometry to lines and circles","Work with 2D vectors"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- NG SS 3
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('NG','NG_SS3','NG_MATH','Mathematics',
'[{"name":"Revision and Extension","topics":[{"name":"Number and Algebra","subtopics":["Comprehensive revision of all algebra topics","Past WAEC questions","Common errors and how to avoid them"]},{"name":"Geometry and Trigonometry","subtopics":["Comprehensive revision","3D trigonometry","Sine rule","Cosine rule","Area of triangle using trigonometry"]},{"name":"Calculus","subtopics":["Revision of differentiation and integration","Application questions","WAEC past question practice"]}]},{"name":"Further Topics","topics":[{"name":"Sequences and Series","subtopics":["Arithmetic progression: nth term, sum","Geometric progression: nth term, sum","Sum to infinity","Real-life applications"]},{"name":"Permutations and Combinations","subtopics":["Factorial notation","Permutations","Combinations","Probability using combinatorics"]}]},{"name":"Examination Preparation","topics":[{"name":"WAEC / NECO Exam Technique","subtopics":["Answering WAEC paper 1 (objectives)","Answering WAEC paper 2 (theory)","Time management in exams","Common question types","Practice timed papers"]}]}]',
'{"by_end_of_year":["Apply sine and cosine rules to triangles","Work with arithmetic and geometric progressions","Solve problems using permutations and combinations","Demonstrate exam technique for WAEC and NECO","Complete timed past papers confidently"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- ══════════════════════════════════════════════
-- ENGLAND MATHEMATICS
-- ══════════════════════════════════════════════

-- GB Reception
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_REC','GB_MATH','Mathematics',
'[{"name":"Number","topics":[{"name":"Counting","subtopics":["Counting to 10 reliably","Counting to 20","Subitising small quantities","Matching numerals to quantities"]},{"name":"Number Relationships","subtopics":["One more and one less","Comparing groups using more, fewer, same","Composition of numbers to 5 and 10"]}]},{"name":"Shape, Space and Measure","topics":[{"name":"Shape","subtopics":["Recognising and naming common 2D shapes","Recognising and naming common 3D shapes","Describing position using positional language"]},{"name":"Measurement","subtopics":["Comparing sizes: bigger, smaller, heavier, lighter","Sequencing events: morning, afternoon, night","Ordering by length, weight, capacity"]}]}]',
'{"by_end_of_year":["Count reliably to 20","Subitise quantities to 5","Compare groups and use mathematical language","Recognise common 2D and 3D shapes","Order objects by size, weight and capacity"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 1
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y1','GB_MATH','Mathematics',
'[{"name":"Number and Place Value","topics":[{"name":"Numbers to 100","subtopics":["Counting to 100 forwards and backwards","Reading and writing numbers to 100","Tens and ones","Comparing and ordering numbers to 100"]},{"name":"Number Facts","subtopics":["Number bonds to 10 and 20","Doubles and near doubles","Odd and even numbers"]}]},{"name":"Addition and Subtraction","topics":[{"name":"Mental Strategies","subtopics":["Adding and subtracting one-digit numbers","Adding and subtracting within 20","Counting on and back","Number lines"]},{"name":"Written Methods","subtopics":["Recording addition and subtraction","Missing number problems"]}]},{"name":"Multiplication and Division","topics":[{"name":"Introduction","subtopics":["Counting in 2s, 5s and 10s","Sharing and grouping equally","Arrays"]}]},{"name":"Fractions","topics":[{"name":"Basic Fractions","subtopics":["Half and quarter of shapes","Half and quarter of quantities","Finding three quarters"]}]},{"name":"Measurement","topics":[{"name":"Length and Weight","subtopics":["Measuring using non-standard units","Centimetres and metres introduction","Grams and kilograms introduction"]},{"name":"Time","subtopics":["Days of the week","Months and seasons","Telling time to the hour and half hour"]}]},{"name":"Geometry","topics":[{"name":"Properties of Shapes","subtopics":["2D shapes: sides and vertices","3D shapes: faces, edges, vertices","Patterns and symmetry"]},{"name":"Position and Direction","subtopics":["Describing position","Whole, half, quarter turns","Clockwise and anti-clockwise"]}]}]',
'{"by_end_of_year":["Count, read and write numbers to 100","Know number bonds to 20","Add and subtract within 20 mentally","Count in 2s, 5s and 10s","Tell time to the hour and half hour","Recognise halves and quarters"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 2
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y2','GB_MATH','Mathematics',
'[{"name":"Number and Place Value","topics":[{"name":"Numbers to 100","subtopics":["Place value: tens and ones","Reading and writing numbers to 100 in words","Comparing using < > =","Ordering sequences"]}]},{"name":"Addition and Subtraction","topics":[{"name":"Mental and Written","subtopics":["Adding and subtracting 2-digit numbers mentally","Column addition and subtraction","Inverse operations","Checking answers"]}]},{"name":"Multiplication and Division","topics":[{"name":"Times Tables","subtopics":["2, 5 and 10 times tables","Multiplication and division facts","Solving problems using arrays","Odd and even results"]}]},{"name":"Fractions","topics":[{"name":"Fractions of Shapes and Sets","subtopics":["Thirds, quarters, halves","Fractions of quantities","Simple equivalences: 2/4 = 1/2"]}]},{"name":"Measurement","topics":[{"name":"Length, Mass and Capacity","subtopics":["Measuring in cm and m","Measuring in kg and g","Measuring in ml and l","Choosing appropriate units"]},{"name":"Time","subtopics":["Telling time to quarter past and to","Duration in minutes and hours","Calendars"]},{"name":"Money","subtopics":["Pounds and pence","Combining amounts","Giving change"]}]},{"name":"Geometry","topics":[{"name":"Properties of Shapes","subtopics":["Identifying 2D and 3D shapes","Lines of symmetry","Sorting by properties"]},{"name":"Position and Direction","subtopics":["Directions: north, south, east, west","Following and giving directions"]}]},{"name":"Statistics","topics":[{"name":"Data Handling","subtopics":["Tally charts","Block diagrams","Pictograms","Answering questions from data"]}]}]',
'{"by_end_of_year":["Know 2, 5 and 10 times tables","Add and subtract 2-digit numbers with column method","Find fractions of shapes and quantities","Tell time to quarter past and to","Read and interpret simple graphs"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 3
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y3','GB_MATH','Mathematics',
'[{"name":"Number and Place Value","topics":[{"name":"Numbers to 1000","subtopics":["Place value: hundreds, tens, ones","Comparing and ordering to 1000","Counting in 50s and 100s","Roman numerals I to XII"]}]},{"name":"Addition and Subtraction","topics":[{"name":"Mental and Written","subtopics":["Adding and subtracting 3-digit numbers","Formal column method","Estimating and checking","Problems with missing numbers"]}]},{"name":"Multiplication and Division","topics":[{"name":"Times Tables","subtopics":["3, 4 and 8 times tables","Multiplying 2-digit by 1-digit","Dividing 2-digit by 1-digit","Factor pairs"]}]},{"name":"Fractions","topics":[{"name":"Fractions","subtopics":["Counting in tenths","Comparing fractions with same denominator","Adding fractions with same denominator","Fractions on a number line"]}]},{"name":"Measurement","topics":[{"name":"Length, Perimeter and Area","subtopics":["Measuring in mm, cm, m, km","Calculating perimeter","Area by counting squares"]},{"name":"Time","subtopics":["Telling time to the minute","24-hour clock","Calculating duration"]},{"name":"Mass and Capacity","subtopics":["Measuring in g, kg, ml, l","Reading scales"]}]},{"name":"Geometry","topics":[{"name":"Shapes and Angles","subtopics":["Types of angles: right, acute, obtuse","Horizontal and vertical lines","Parallel and perpendicular lines"]}]},{"name":"Statistics","topics":[{"name":"Graphs and Charts","subtopics":["Bar charts","Pictograms","Tables","Answering and posing questions"]}]}]',
'{"by_end_of_year":["Know 3, 4 and 8 times tables","Add and subtract 3-digit numbers using column method","Count in tenths and add fractions","Measure perimeter and area","Tell time to the minute and use 24-hour clock"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 4
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y4','GB_MATH','Mathematics',
'[{"name":"Number and Place Value","topics":[{"name":"Numbers to 10,000","subtopics":["Place value to ten-thousands","Negative numbers","Roman numerals to 100","Rounding to nearest 10, 100, 1000"]}]},{"name":"Addition and Subtraction","topics":[{"name":"Written Methods","subtopics":["Column addition and subtraction with 4-digit numbers","Estimating","Inverse operations","Multi-step word problems"]}]},{"name":"Multiplication and Division","topics":[{"name":"All Times Tables","subtopics":["All tables to 12 x 12","Multiplying 3-digit by 1-digit","Dividing 3-digit by 1-digit","Correspondence problems"]}]},{"name":"Fractions and Decimals","topics":[{"name":"Fractions","subtopics":["Equivalent fractions","Adding fractions beyond one whole","Subtracting fractions","Fractions greater than 1"]},{"name":"Decimals","subtopics":["Tenths and hundredths","Comparing and ordering decimals","Rounding decimals","Dividing by 10 and 100"]}]},{"name":"Measurement","topics":[{"name":"Area and Perimeter","subtopics":["Area of rectangles","Perimeter of rectilinear shapes","Relating area and perimeter"]},{"name":"Conversion","subtopics":["Converting units of measurement","Analogue to digital time","12 and 24-hour clock"]}]},{"name":"Geometry","topics":[{"name":"Shapes and Symmetry","subtopics":["Acute, obtuse, right angles","Comparing and classifying shapes","Lines of symmetry","Coordinates in first quadrant"]}]},{"name":"Statistics","topics":[{"name":"Graphs","subtopics":["Discrete and continuous data","Bar charts","Time graphs","Interpreting data"]}]}]',
'{"by_end_of_year":["Know all times tables to 12","Add and subtract 4-digit numbers","Find equivalent fractions and add fractions","Understand tenths and hundredths","Calculate area and perimeter of rectangles","Use coordinates in first quadrant"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 5
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y5','GB_MATH','Mathematics',
'[{"name":"Number and Place Value","topics":[{"name":"Numbers to 1,000,000","subtopics":["Reading and writing numbers to 1,000,000","Place value","Counting in powers of 10","Negative numbers on a number line","Rounding to any power of 10"]}]},{"name":"Four Operations","topics":[{"name":"Multiplication and Division","subtopics":["Multiplying 4-digit by 2-digit","Long division","BODMAS","Prime numbers to 100","Multiples, factors and prime factors","Square and cube numbers"]}]},{"name":"Fractions, Decimals and Percentages","topics":[{"name":"Fractions","subtopics":["Comparing and ordering fractions","Adding and subtracting with different denominators","Multiplying fractions by whole numbers","Mixed numbers"]},{"name":"Decimals","subtopics":["Thousandths","Rounding decimals","Multiplying and dividing by 10, 100, 1000"]},{"name":"Percentages","subtopics":["Percentage as fraction and decimal","Percentage of amounts","Percentage increase and decrease"]}]},{"name":"Ratio and Proportion","topics":[{"name":"Ratio","subtopics":["Ratio notation","Dividing in a ratio","Scale factors","Unequal sharing"]}]},{"name":"Measurement","topics":[{"name":"Area, Perimeter and Volume","subtopics":["Area of triangles and parallelograms","Volume of cuboids","Estimating volume","Converting units"]}]},{"name":"Geometry","topics":[{"name":"Shapes and Angles","subtopics":["Angles in triangles and quadrilaterals","Regular and irregular polygons","Reflection and translation","Coordinates in all 4 quadrants"]}]},{"name":"Statistics","topics":[{"name":"Line Graphs and Tables","subtopics":["Interpreting and drawing line graphs","Timetables","Two-way tables","Mean, median, mode, range"]}]}]',
'{"by_end_of_year":["Read and write numbers to 1,000,000","Multiply 4-digit by 2-digit numbers","Add and subtract fractions with different denominators","Find percentages of amounts","Calculate area of triangles and volume of cuboids","Use coordinates in all 4 quadrants"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 6
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y6','GB_MATH','Mathematics',
'[{"name":"Number","topics":[{"name":"Place Value and Arithmetic","subtopics":["Numbers to 10,000,000","Order of operations","Long multiplication and division","Multi-step word problems","Common factors and multiples","Prime factorisation"]}]},{"name":"Fractions, Decimals and Percentages","topics":[{"name":"Fractions","subtopics":["Dividing fractions by whole numbers","Multiplying fractions by fractions","Adding and subtracting mixed numbers","Fractions in context"]},{"name":"Decimals and Percentages","subtopics":["Decimal multiplication and division","Percentage change","Percentage problems","Equivalence of fractions, decimals and percentages"]}]},{"name":"Ratio and Proportion","topics":[{"name":"Ratio","subtopics":["Ratio and proportion problems","Unequal sharing","Recipes and scale","Percentage as ratio"]}]},{"name":"Algebra","topics":[{"name":"Introduction to Algebra","subtopics":["Using letters to represent unknowns","Simple formulae","Linear sequences","Solving equations","Expressing missing number problems algebraically"]}]},{"name":"Measurement","topics":[{"name":"Area, Perimeter and Volume","subtopics":["Area of triangles, parallelograms and trapeziums","Volume of cuboids","Surface area","Converting units"]}]},{"name":"Geometry","topics":[{"name":"Angles and Shapes","subtopics":["Angles in polygons","Circles: radius, diameter, circumference","3D shapes and nets","Coordinates: translations and reflections"]},{"name":"SATs Preparation","subtopics":["Past KS2 SATs questions","Reasoning questions","Arithmetic test practice","Problem-solving strategies"]}]},{"name":"Statistics","topics":[{"name":"Graphs and Averages","subtopics":["Pie charts","Line graphs","Mean from frequency tables","Interpreting data"]}]}]',
'{"by_end_of_year":["Multiply fractions by fractions","Divide fractions by whole numbers","Solve percentage change problems","Use algebra to express formulae and solve equations","Find area of triangles and trapeziums","Prepare for KS2 SATs"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 7
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y7','GB_MATH','Mathematics',
'[{"name":"Number","topics":[{"name":"Integers and Directed Numbers","subtopics":["Operations with negative numbers","Order of operations (BIDMAS)","Powers and roots","Prime factorisation","LCM and HCF"]},{"name":"Fractions, Decimals and Percentages","subtopics":["All operations with fractions","Recurring decimals","Percentage change","Reverse percentage","Interest calculations"]}]},{"name":"Algebra","topics":[{"name":"Expressions and Equations","subtopics":["Collecting like terms","Expanding single brackets","Factorising","Solving linear equations","Substitution","Formulae"]},{"name":"Sequences","subtopics":["Term-to-term rule","nth term of linear sequence","Geometric sequences"]}]},{"name":"Ratio and Proportion","topics":[{"name":"Ratio","subtopics":["Simplifying ratios","Dividing in a ratio","Direct proportion","Inverse proportion","Best value problems"]}]},{"name":"Geometry","topics":[{"name":"Angles","subtopics":["Angles in parallel lines","Angles in polygons","Bearings","Constructions with compass and ruler"]},{"name":"Area and Perimeter","subtopics":["Area of composite shapes","Circumference and area of circles","Arc length and sector area"]}]},{"name":"Statistics and Probability","topics":[{"name":"Statistics","subtopics":["Mean, median, mode, range","Frequency tables","Bar charts and histograms","Scatter graphs: correlation","Line of best fit"]},{"name":"Probability","subtopics":["Probability scale","Relative frequency","Sample space diagrams","Mutually exclusive events"]}]}]',
'{"by_end_of_year":["Work confidently with negative numbers and BIDMAS","Solve linear equations and use formulae","Apply ratio and proportion to real-life problems","Calculate circumference and area of circles","Interpret scatter graphs and probability"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 8
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y8','GB_MATH','Mathematics',
'[{"name":"Number","topics":[{"name":"Standard Form and Surds","subtopics":["Standard form notation","Calculations in standard form","Simplifying surds","Rationalising the denominator"]}]},{"name":"Algebra","topics":[{"name":"Expanding and Factorising","subtopics":["Expanding double brackets","Factorising quadratics","Difference of two squares"]},{"name":"Simultaneous Equations","subtopics":["Solving by elimination","Solving by substitution","Graphical solution","Word problems"]},{"name":"Inequalities","subtopics":["Solving linear inequalities","Graphing on a number line","Quadratic inequalities introduction"]}]},{"name":"Graphs","topics":[{"name":"Linear and Quadratic Graphs","subtopics":["y = mx + c","Parallel and perpendicular lines","Plotting quadratic curves","Equation of a curve from a graph"]}]},{"name":"Geometry","topics":[{"name":"Pythagoras and Trigonometry","subtopics":["Pythagoras theorem: 2D and 3D","Sin, cos, tan","Finding angles and sides","Exact trigonometric values"]},{"name":"Transformation","subtopics":["Reflection, rotation, translation","Enlargement with negative scale factor","Describing transformations"]}]},{"name":"Statistics","topics":[{"name":"Data Analysis","subtopics":["Cumulative frequency graphs","Box plots","Comparing distributions","Sampling methods"]}]}]',
'{"by_end_of_year":["Use standard form confidently","Expand double brackets and factorise quadratics","Solve simultaneous equations","Apply Pythagoras and trigonometry","Construct and interpret cumulative frequency graphs"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 9
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y9','GB_MATH','Mathematics',
'[{"name":"Number and Algebra","topics":[{"name":"Further Algebra","subtopics":["Quadratic equations: factorising, formula, completing the square","Algebraic fractions","Functions and inverse functions","Composite functions"]},{"name":"Sequences and Series","subtopics":["Arithmetic sequences: nth term","Geometric sequences","Quadratic sequences"]}]},{"name":"Graphs and Functions","topics":[{"name":"Advanced Graphs","subtopics":["Cubic and reciprocal graphs","Exponential graphs","Transformation of graphs","Gradient of a curve"]}]},{"name":"Geometry","topics":[{"name":"Circle Theorems","subtopics":["All circle theorems","Proof using circle theorems"]},{"name":"Mensuration","subtopics":["Volume and surface area of spheres, cones, pyramids","Frustums","Density, mass, volume"]},{"name":"Vectors","subtopics":["Vector notation","Adding and subtracting vectors","Scalar multiplication","Vector geometry proofs"]}]},{"name":"Statistics and Probability","topics":[{"name":"Probability","subtopics":["Tree diagrams","Conditional probability","Venn diagrams","Combined events"]},{"name":"Statistics","subtopics":["Histograms with unequal class widths","Moving averages","Regression lines"]}]}]',
'{"by_end_of_year":["Solve quadratic equations by all methods","Transform and interpret graphs of functions","Apply all circle theorems","Calculate volumes of all 3D shapes","Work with vectors and conditional probability"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 10
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y10','GB_MATH','Mathematics',
'[{"name":"GCSE Number","topics":[{"name":"Number","subtopics":["Exact calculations with surds and pi","Upper and lower bounds","Error intervals","Recurring decimals to fractions","Index laws"]}]},{"name":"GCSE Algebra","topics":[{"name":"Algebra","subtopics":["Solving quadratics by all methods","Simultaneous equations: linear and quadratic","Inequalities: linear and quadratic","Iterative methods","Algebraic proof"]},{"name":"Graphs","subtopics":["Distance-time and velocity-time graphs","Area under a curve","Gradient as a rate of change","Transformations of graphs"]}]},{"name":"GCSE Ratio and Proportion","topics":[{"name":"Ratio, Proportion and Rates of Change","subtopics":["Direct and inverse proportion","Compound measures","Percentage problems","Growth and decay"]}]},{"name":"GCSE Geometry","topics":[{"name":"Geometry and Measures","subtopics":["Constructions and loci","Similarity and congruence","Trigonometry: sine and cosine rule","Area of non-right triangles","3D trigonometry"]},{"name":"Circle Theorems","subtopics":["All circle theorems with proof"]}]},{"name":"GCSE Statistics and Probability","topics":[{"name":"Statistics","subtopics":["Sampling","Histograms","Cumulative frequency","Comparing distributions"]},{"name":"Probability","subtopics":["Combined events","Conditional probability","Venn diagrams","Tree diagrams"]}]}]',
'{"by_end_of_year":["Apply upper and lower bounds","Solve simultaneous linear and quadratic equations","Apply sine and cosine rules","Prove circle theorems","Interpret distance-time and velocity-time graphs","Calculate conditional probability"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 11
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y11','GB_MATH','Mathematics',
'[{"name":"GCSE Revision and Exam Preparation","topics":[{"name":"Comprehensive Revision","subtopics":["Full revision of all GCSE topics","Past paper practice","Identifying and addressing weaknesses","Exam technique: showing working","Time management in GCSE exams"]},{"name":"Higher Topics","subtopics":["Functions: f(x) notation, inverse, composite","Proof","Algebraic fractions","Further surds","Geometric proof"]},{"name":"Problem Solving","subtopics":["Multi-step problems","Functional maths","Real-life context problems","Reasoning and justification"]}]},{"name":"GCSE Final Topics","topics":[{"name":"Data and Probability","subtopics":["Capture-recapture method","Moving averages","Further probability"]},{"name":"Geometry","subtopics":["Further mensuration","Vectors in proofs","3D coordinates"]}]}]',
'{"by_end_of_year":["Complete all Higher GCSE content","Attempt and complete past GCSE papers under timed conditions","Apply algebraic and geometric proof","Achieve target grade in GCSE Mathematics"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 12
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y12','GB_MATH','Mathematics',
'[{"name":"Pure Mathematics","topics":[{"name":"Algebra and Functions","subtopics":["Laws of indices","Surds","Quadratic functions: completing the square","Simultaneous equations","Inequalities","Polynomials: factor theorem, remainder theorem","Graphs of functions","Transformations"]},{"name":"Coordinate Geometry","subtopics":["Equation of a line","Equation of a circle","Intersection of lines and curves"]},{"name":"Sequences and Series","subtopics":["Arithmetic sequences and series","Sigma notation","Geometric sequences and series","Sum to infinity"]},{"name":"Trigonometry","subtopics":["Sine, cosine, tangent rules","Radian measure","Arc length and sector area","Trigonometric identities","Solving trig equations"]},{"name":"Exponentials and Logarithms","subtopics":["Exponential functions","Logarithms and laws","Natural logarithm","Solving exponential equations","Modelling with exponentials"]},{"name":"Differentiation","subtopics":["Differentiating polynomials","Chain rule","Product rule","Quotient rule","Tangents and normals","Stationary points","Optimisation"]},{"name":"Integration","subtopics":["Indefinite integration","Definite integration","Area under a curve","Trapezium rule"]}]},{"name":"Statistics","topics":[{"name":"Statistical Sampling","subtopics":["Sampling methods","Large Data Set","Interpreting data"]},{"name":"Probability","subtopics":["Probability distributions","Binomial distribution","Normal distribution introduction"]},{"name":"Hypothesis Testing","subtopics":["Null and alternative hypothesis","Critical region","One and two-tailed tests"]}]},{"name":"Mechanics","topics":[{"name":"Kinematics","subtopics":["SUVAT equations","Displacement-time and velocity-time graphs","Variable acceleration"]},{"name":"Forces","subtopics":["Newton laws of motion","Resolving forces","Connected particles","Friction"]}]}]',
'{"by_end_of_year":["Differentiate and integrate polynomial, exponential and trigonometric functions","Apply chain, product and quotient rules","Work with arithmetic and geometric series","Apply the binomial distribution and hypothesis testing","Solve kinematics problems using SUVAT"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;

-- GB Year 13
insert into local_curricula (country_code,year_group_code,subject_code,subject,topics,competencies)
values ('GB','GB_Y13','GB_MATH','Mathematics',
'[{"name":"Pure Mathematics","topics":[{"name":"Proof","subtopics":["Proof by contradiction","Proof by exhaustion","Disproof by counterexample"]},{"name":"Algebra and Functions","subtopics":["Partial fractions","Modulus function","Composite and inverse functions","Parametric equations"]},{"name":"Series and Limits","subtopics":["Binomial expansion for any rational n","Maclaurin series","Convergence"]},{"name":"Trigonometry","subtopics":["Compound angle formulae","Double angle formulae","R cos(x+a) form","Inverse trigonometric functions","Reciprocal trig functions: sec, cosec, cot"]},{"name":"Differentiation","subtopics":["Differentiating trig, exponential, logarithmic functions","Implicit differentiation","Parametric differentiation","Second derivatives"]},{"name":"Integration","subtopics":["Integration by substitution","Integration by parts","Integration of partial fractions","Differential equations","Volumes of revolution"]},{"name":"Vectors","subtopics":["3D vectors","Scalar product","Angle between vectors","Vector equations of lines"]}]},{"name":"Statistics","topics":[{"name":"Regression and Correlation","subtopics":["Product moment correlation coefficient","Regression lines","Hypothesis testing for correlation"]},{"name":"Probability Distributions","subtopics":["Normal distribution","Standardisation","Normal approximation to binomial","Confidence intervals"]}]},{"name":"Mechanics","topics":[{"name":"Moments and Equilibrium","subtopics":["Moments","Equilibrium of a rigid body","Centre of mass"]},{"name":"Further Kinematics","subtopics":["Variable acceleration using calculus","Projectile motion"]}]}]',
'{"by_end_of_year":["Apply all differentiation and integration techniques","Work with parametric and implicit equations","Apply all trigonometric identities","Use normal distribution and conduct hypothesis tests","Solve differential equations","Prepare for A-Level Mathematics examinations"]}')
on conflict (country_code,year_group_code,subject_code) do update set topics=excluded.topics,competencies=excluded.competencies;
